### ISSUE TITLE
files under integration tests doesn't seem to trigger CI correctly.

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#1639]
```   
   - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            crates/youki: crates/youki/**
            crates/libcontainer: crates/libcontainer/**
            crates/libcgroups: crates/libcgroups/**

            tests/rust-integration-tests/runtimetest: ./tests/rust-integration-tests/runtimetest
            tests/rust-integration-tests/integration_test: ./tests/rust-integration-tests/integration_test
            tests/rust-integration-tests/test_framework: ./tests/rust-integration-tests/test_framework
```
The highlight part looks incorrect. Requires more investigation.

**Comment by lengrongfu** [comment]
Looks like there is something wrong with the rules, I can fix it.

https://github.com/marketplace/actions/paths-changes-filter
```yaml
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

    # run only if 'backend' files were changed
    - name: backend tests
      if: steps.filter.outputs.backend == 'true'
      run: ...

    # run only if 'frontend' files were changed
    - name: frontend tests
      if: steps.filter.outputs.frontend == 'true'
      run: ...

    # run if 'backend' or 'frontend' files were changed
    - name: e2e tests
      if: steps.filter.outputs.backend == 'true' || steps.filter.outputs.frontend == 'true'
      run: ...
```
