### ISSUE TITLE
youki need seccomp unconfined when runc/crun don't

### ISSUE THREAD

**Issue by martadinata666** [containers/youki#2022]
As the title said, for some reason youki need `seccomp unconfined`, two containers that I tested was mariadb and jellyfin.

Jellyfin log
```
jellyfin_server  | Failed to create CoreCLR, HRESULT: 0x80070008
jellyfin_server exited with code 137
```

Mariadb log
```
documize-db-1  | 2023-06-08 13:56:14+07:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.2+maria~debsid started.
documize-db-1  | 2023-06-08 13:56:14+07:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
documize-db-1  | 	command was: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --verbose --help --log-bin-index=/tmp/tmp.axLXmY9ftc
documize-db-1  | 	Can't initialize timers
documize-db-1 exited with code 0

```

Runtime:
Kernel 6.3
Ubuntu Jammy
Docker 24.0.2

Compiler
Rust 1.70

**Comment by utam0k** [comment]
👋 Hi, @martadinata666. Thanks for your report. May I ask you to give us more specific commands to reproduce the problem you pointed out?

**Comment by martadinata666** [comment]
Hi, thanks for the response.

Let me start with minimal compose startup 

```
services:
  db:
    image: mariadb:lts
    environment:
      - MARIADB_ROOT_PASSWORD=mariadbnc
      - TZ=Asia/Jakarta
      - MARIADB_DATABASE=dummy
      - MARIADB_USER=dummyuser
      - MARIADB_PASSWORD=dummypass
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
  db:
```
In this setup that docker by default using `runc` the mariadb container start correctly, now on to youki runtime
```
  db:
    image: mariadb:lts
    runtime: youki
    environment:
      - MARIADB_ROOT_PASSWORD=mariadbnc
      - TZ=Asia/Jakarta
      - MARIADB_DATABASE=dummy
      - MARIADB_USER=dummyuser
      - MARIADB_PASSWORD=dummypass
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
  db:
```
In this compose I define runtime with youki, that should be start container correctly, but unfortunately it don't, like the original post. `Mariadb throw error about fail initialize timers`
```
Attaching to mariadb-test-db-1
mariadb-test-db-1  | 2023-06-08 18:21:01+07:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.11.3+maria~ubu2204 started.
mariadb-test-db-1  | 2023-06-08 18:21:01+07:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
mariadb-test-db-1  | 	command was: mariadbd --verbose --help
mariadb-test-db-1  | 	Can't initialize timers
mariadb-test-db-1 exited with code 0
```

So I'm looking around and find
* https://github.com/MariaDB/mariadb-docker/issues/434
* https://docs.linuxserver.io/faq
tldr; it about old docker version that upgrade docker will do the trick, but this shouldn't the issue as my docker version is `24.0.2` far ahead newer.

But just out of curiosity I follow the guide, updating my compose to
```
services:
  db:
    image: mariadb:lts
    runtime: youki
    security_opt:
      - seccomp=unconfined
    environment:
      - MARIADB_ROOT_PASSWORD=mariadbnc
      - TZ=Asia/Jakarta
      - MARIADB_DATABASE=dummy
      - MARIADB_USER=dummyuser
      - MARIADB_PASSWORD=dummypass
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
  db:
```
And unexpectedly it starts correctly, so I don't know why youki need seccomp tweak when other runtimes doesn't. FYI `crun` also start container correctly without seccomp tweak. 🤔
